services:
    gdn-bot:
        image: 'f40gko8scg4s8wk8okc4wocc:latest'
        container_name: gdn-bot
        restart: unless-stopped
        expose:
            - '80'
        networks:
            x0ckso48ock480gc008o4w0s:
                aliases:
                    - gdn-bot
        mem_limit: '0'
        memswap_limit: '0'
        mem_swappiness: 60
        mem_reservation: '0'
        cpus: 0.0
        cpu_shares: 1024
        env_file:
            - .env
        labels:
            - traefik.enable=true
            - traefik.http.middlewares.gzip.compress=true
            - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
            - traefik.http.routers.http-0-f40gko8scg4s8wk8okc4wocc.entryPoints=http
            - traefik.http.routers.http-0-f40gko8scg4s8wk8okc4wocc.middlewares=gzip
            - 'traefik.http.routers.http-0-f40gko8scg4s8wk8okc4wocc.rule=Host(`f40gko8scg4s8wk8okc4wocc.138.199.148.98.sslip.io`) && PathPrefix(`/`)'
            - traefik.http.routers.http-0-f40gko8scg4s8wk8okc4wocc.service=http-0-f40gko8scg4s8wk8okc4wocc
            - traefik.http.services.http-0-f40gko8scg4s8wk8okc4wocc.loadbalancer.server.port=80
            - 'caddy_0.encode=zstd gzip'
            - 'caddy_0.handle_path.0_reverse_proxy={{upstreams 80}}'
            - 'caddy_0.handle_path=/*'
            - caddy_0.header=-Server
            - 'caddy_0.try_files={path} /index.html /index.php'
            - 'caddy_0=http://f40gko8scg4s8wk8okc4wocc.138.199.148.98.sslip.io'
            - caddy_ingress_network=x0ckso48ock480gc008o4w0s
            - coolify.managed=true
            - coolify.version=4.0.0-beta.418
            - coolify.applicationId=2
            - coolify.type=application
            - coolify.name=f40gko8scg4s8wk8okc4wocc
            - coolify.resourceName=gdn-bot
            - coolify.projectName=bot-grew-solutions
            - coolify.serviceName=gdn-bot
            - coolify.environmentName=production
            - coolify.pullRequestId=0
        volumes:
            - '/data/coolify/applications/gdn-bot/app:/app'
networks:
    x0ckso48ock480gc008o4w0s:
        external: true
        name: x0ckso48ock480gc008o4w0s
        attachable: true
